# -*- coding: utf-8 -*-
"""new_main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NVs1ttFtKsPZw_7_SGfYLu25Gswqacna
"""


import face_recognition
import tensorlayerx as tlx
import cv2
import numpy as np
import io
import subprocess
import train
def face_reid(unknowface,suspect_image):

  unknowface = train.Generate_high_resolution(unknowface)
  rgb = np.ascontiguousarray(unknowface[:, :, ::-1])
  # Initialize some variables
  face_locations = []
  face_encodings = []
  face_names = []

  try:
      suspect_image_encoding = face_recognition.face_encodings(suspect_image)[0]
      face_encodings = face_recognition.face_encodings(rgb)[0]

  except IndexError:
      print("I wasn't able to locate any faces in at least one of the images. Check the image files. Aborting...")
      quit()
  known_faces = [
      suspect_image_encoding
  ]

  # results is an array of True/False telling if the unknown face matched anyone in the known_faces array

  results = face_recognition.compare_faces(known_faces, face_encodings)

  print("Is the unknown face a picture of target? {}".format(results[0]))
  print("Is the unknown face a new person that we've never seen before? {}".format(not True in results))


  return results[0]

